version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      pip-major:
        patterns:
          - "*"
        update-types:
        - "major"
      pip-minor:
        patterns:
          - "*"
        update-types:
        - "minor"
        - "patch"
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      npm-major:
        patterns:
          - "*"
        update-types:
        - "major"
      npm-minor:
        patterns:
          - "*"
        update-types:
        - "minor"
        - "patch"
  - package-ecosystem: "github-actions"
    # Workflow files stored in the
    # default location of `.github/workflows`
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      github-action-group:
        patterns:
          - "*"
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
